### PR TITLE
Update gradle & update dependencies & add CI config

### PR DESCRIPTION
**Pull request by Goooler**
- 依赖升级，适配 ExoPlayer 2.14.0
- 部分 gradle 配置简化
- 添加 gitIgnore 规则
- 添加 github action 配置，在提交和 PR 时自动编译，验证合法性。你合进去之后可能需要在 actions 那里开启一下
- 添加可空性注解，增强推断效果
- 部分已废弃方法替换和删除
- ndk 库移入 `src/main/jniLibs` 文件夹内，这是新版 agp 支持的默认路径，不需要额外声明

### CODE REVIEW

**Comment by Goooler** [comment]
我看到发布 8.1.5 之前有[把 gradle 和 AGP 版本退回去的提交](https://github.com/CarGuo/GSYVideoPlayer/commit/868f5b9910ae43173ca9cc17e83d85ba089ade0a)，不知道是出于什么样的考虑 @CarGuo

**Comment by CarGuo** [comment]
@Goooler 因为有个急问题需要打release，jitpack 发布编译，发现用新版本暂时好像对某些注解方式弃用编译错误，所以暂时先回了

**Comment by Goooler** [comment]
> 需要

那把这个 PR 合进去之后调一下发布的工具？

**Comment by Goooler** [comment]
> @Goooler 因为有个急问题需要打release，jitpack 发布编译，发现用新版本暂时好像对某些注解方式弃用编译错误，所以暂时先回了

那把这个 PR 合进去之后调一下发布的工具？

**Comment by CarGuo** [comment]
@Goooler  hello ，你这个 pr 内容有点多，可不可以麻烦测试下 debug 下和 release 能否正常运行，然后看看 exo 和 ijk 能正常播放和关闭吗？

**Comment by Goooler** [comment]
> @Goooler hello ，你这个 pr 内容有点多，可不可以麻烦测试下 debug 下和 release 能否正常运行，然后看看 exo 和 ijk 能正常播放和关闭吗？

试过了没啥问题，我把 app 模块下的混淆也开了，能正常播放。

**Comment by CarGuo** [comment]
> Configure project :
Gradle version Gradle 7.1

> Configure project :app
WARNING:: DSL element 'annotationProcessorOptions.includeCompileClasspath' is obsolete.
It will be removed in version 7.0 of the Android Gradle plugin.
It does not do anything and AGP no longer includes annotation processors added on your project's compile classpath

FAILURE: Build failed with an exception.

* Where:
Script '/script/maven-plugin.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Failed to apply plugin 'com.github.dcendents.android-maven'.
   > Could not create plugin of type 'AndroidMavenPlugin'.
      > Could not generate a decorated class for type AndroidMavenPlugin.
         > org/gradle/api/publication/maven/internal/MavenPomMetaInfoProvider

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
Build tool exit code: 0
Looking for artifacts...
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Looking for pom.xml in build directory and ~/.m2
2021-07-08T10:26:29.727373214Z
Exit code: 0

ERROR: No build artifacts found

**Comment by CarGuo** [comment]
> https://stackoverflow.com/questions/67599438/gradle-7-and-jitpack-io-runs-into-error-during-publish

**Comment by Goooler** [comment]
> > https://stackoverflow.com/questions/67599438/gradle-7-and-jitpack-io-runs-into-error-during-publish

要不用 #3326 这个提交发布一下试试？

**Comment by CarGuo** [comment]
可以了

**Pull request merged**
